### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/Fluoride_Gravity#4]
09/08/2018

- [ ] Figure out if we will have a separate Github repo (talk to the other fluoride team after the first Monday night class)
- [ ] Fix the report from summer 2018
- [ ] Send Monroe an email about the new probe (whether or not it has been purchased)
- [ ] Set up Calibration sheet on google drive 
- [ ] Test flow rates of the gravity powered system since we have the set-up now
- [ ] Work on Python code to calculate head loss and appropriate height for constant head tanks 
- [ ] Read Thesis in the Challenges document thesis 
- [ ] Write out a fabrication manual and operation manual for the gravity-powered system
- [ ] Calculate amount of coagulant entering the system using the balance
- [ ] Using both old and new probe to confirm calibration curve
- [ ] Run tests of different concentration of fluoride and coagulant on the gravity-powered system
- [ ] Research how to deal with the waste stream, i.e. how to separate fluoride from the aluminum? Can adjusting pH help?
- [ ] New sed tank bottom geometry
